### ISSUE TITLE
Images seem to only generate for 1st subdirectory

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#1]
### My Music Folder Directory Tree strucuture + visual look:

```
D:.
├───Alan Walker
├───Imagine Dragons
├───Kygo
├───Lauv
│   ├───Lauv - I met you when I was 18. (the playlist) - 2018
│   └───Lauv - ~how i'm feeling~ - 2020
├───Maroon 5
├───Monstercat
│   └───Throttle
└───OneRepublic
```
![image](https://user-images.githubusercontent.com/39442192/111903239-3b888780-8a67-11eb-84e4-c8480099bd56.png)

### Input For musicdl.exe:
![image](https://user-images.githubusercontent.com/39442192/111903386-121c2b80-8a68-11eb-9270-811b24896f66.png)

### Generated Album Art + dat file:
![image](https://user-images.githubusercontent.com/39442192/111903414-3841cb80-8a68-11eb-9fd8-12924d88f5fd.png)
 
#### Dat File: [line marked with `<---------` is the one with sub-directory's album art]
```
music.ui=groove
id=
Faded==0  <---------
Shadows==1
```

### Tree structure + visual look:
```
D:.
└───Throttle
```
![image](https://user-images.githubusercontent.com/39442192/111903490-8d7ddd00-8a68-11eb-83a0-3d5a8aae9209.png)

### Input For musicdl.exe:
![image](https://user-images.githubusercontent.com/39442192/111903602-23196c80-8a69-11eb-875d-9dab66f9232d.png)

### Generated Album Art + dat file:
![image](https://user-images.githubusercontent.com/39442192/111903659-68d63500-8a69-11eb-9577-a9246bbd04b9.png)

### Dat file: [line marked with `<---------` is the one with sub-directory's album art]
```
music.ui=groove
id=
Chasing Clouds==0
Destroy Me==1
Silhouette (Feed Me Remix)==2
Level Days==3
Talk!==4
Worst Part of Heaven==5
Color==6
Reset==7
Gold / YES==8
Upgrade==9
Someone Else==10
Where U Are==11 <---------
Good 4 Me / Union==12

```

---

It appears that images are generated only for the 1st subdirectory.

**Note: All my mp3s have an album art in them**

**Comment by jojo2357** [comment]
What the heck!? It gets all of my subdirectories so could you run it through cmd to get the console output because i have never seen this before.

**Comment by RoguedBear** [comment]
I had to pipe-in the input and pipe-out the console log to a file because the same line was being written by the next log (`\r` i think) and I couldn't get the full output from the command line.

### Case 1 output: 
#### case1.log :
```
Who is this (github username is good, just for naming your files for the library)
MP3 or DAT: Where are your pictures? (fully qualified dir pls)
All done from D:\UserFiles\Music\jj music 2 (0)
Copying image (0) images/Faded.jpg
Copying image (1) images/Shadows.jpg
```

#### Case 1 input:
```
RoguedBear
MP3
D:\UserFiles\Music\jj music
```

### Case 2 output:
#### case2.log : 
```
Who is this (github username is good, just for naming your files for the library)
MP3 or DAT: Where are your pictures? (fully qualified dir pls)
All done from D:\UserFiles\Music\jj music\Monstercat 13 (0)
Copying image (0) images/Chasing Clouds.jpg
Copying image (1) images/Destroy Me.jpg
Copying image (2) images/Silhouette (Feed Me Remix).jpg
Copying image (3) images/Level Days.jpg
Copying image (4) images/Talk!.jpg
Copying image (5) images/Worst Part of Heaven.jpg
Copying image (6) images/Color.jpg
Copying image (7) images/Reset.jpg
Copying image (8) images/Gold  YES.jpg
Copying image (9) images/Upgrade.jpg
Copying image (10) images/Someone Else.jpg
Copying image (11) images/Where U Are.jpg
Copying image (12) images/Good 4 Me  Union.jpg
```


#### Case 2 input:
```
RoguedBear
MP3
D:\UserFiles\Music\jj music\Monstercat
```


---

Should I also post a tree of all the file contents in my music directory to make it easier for you to identify which files belong to a subdirectory?

**Comment by jojo2357** [comment]
@RoguedBear i really dont know what is causing the issue but i have a hunch the newest commit may help. please try that and lmk

**Comment by RoguedBear** [comment]
I ran the new exe, and here's what happened: before making the `archive/` folder as suggested in #2 the output was the same. After making the `archive/` and moving `groove0`, `musicbee0`, `spotify0` into that folder, There's an error in the output and the program halts (not quits)
but, I also see a folder `images/` in the repo root which contains album art **from all the sub-directories** and the file `all.dat` mentioning all the albums in that folder

Log:
```
Who is this (github username is good, just for naming your files for the library)
RoguedBear
MP3 or DAT: MP3
Where are your pictures? (fully qualified dir pls)
D:\UserFiles\Music\jj music
All done from D:\UserFiles\Music\jj music 2 (0)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at Object.fs.readSync (pkg/prelude/bootstrap.js:554:32)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at C:\snapshot\itunes-artwork-finder\musicdl.js
    at Array.forEach (<anonymous>)
    at setupExport (C:\snapshot\itunes-artwork-finder\musicdl.js)
    at C:\snapshot\itunes-artwork-finder\musicdl.js {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}

```

**Comment by jojo2357** [comment]
oh i mustve misspoken. **the archive folder only holds the generated dat files, not the entire output folders** sorry for not being clear there. If the subdirectory issue still persists i honest to goodness don't know where to start since my music folder has nested folders two deep that all work. if you happen to have node, try running the source code instead. I have never packaged js apps before and theres a chance *that* is the issue

**Comment by RoguedBear** [comment]
I ran `musicdl.js` from node after installing `jsmediatags`.
The output and result remains the same.

> If the subdirectory issue still persists i honest to goodness don't know where to start since my music folder has nested folders two deep that all work. 

I would like to point again that, when that error i mentioned came earlier and the program was paused,  there was this `images/` directory which had **all the images** from the subdirectories as intended and `all.dat` containing their respective album names..
so that means the script is extracting the image files correctly from all the subdirectories, but somewhere after that this weird thing happens

**Comment by jojo2357** [comment]
Oh i missed that part. Thanks for reasserting that. Ill take another look but its hard to solve an issue I can't replicate.

**Comment by RoguedBear** [comment]
I can post some of my music library (some songs from a folder) to a google drive link and post it here

**Comment by jojo2357** [comment]
That would be ideal since it probably isnt a machine issue.

**Comment by RoguedBear** [comment]
https://drive.google.com/drive/folders/15hqzhhhAvuK4Blukh2aOZfdutBQu0eE9?usp=sharing
here you go!

**Comment by jojo2357** [comment]
```Who is this (github username is good, just for naming your files for the library)
RougedBear
MP3 or DAT: mp3
Where are your pictures? (fully qualified dir pls)
C:\Users\Public\Music
All done from undefined 15 (0)
Reading archive...
Starting export...
Begin export level 0
Wrapping up exportsimages/Native.jpg
All finnished
```
![image](https://user-images.githubusercontent.com/66704796/112019873-19394d00-8aed-11eb-84f8-bc8ed1a9ac56.png)
```music.ui=groove
id=
Faded==0
End of Time==1
Play==2
Shadows==3
Origins==4
It Ain't Me==5
Slow Grenade==6
I met you when I was 18. (the playlist)==7
~how i'm feeling~==8
Don't Wanna Know==9
Chasing Clouds==10
Silhouette (Feed Me Remix)==11
Where U Are==12
Good 4 Me / Union==13
Native==14
```
Do I win? Ill push it so u can test it

**Comment by RoguedBear** [comment]
Wohooooo!!! Yes it does work 🎉🎉

Thank you for actively working on this issue! 🙇 

(PS: what went wrong tho? 👀 )

**Comment by jojo2357** [comment]
Im using js and there were some sync issues that was causing the program to kill itself too fast. basically it would go, start reading all the folders at once, get some mp3's, read them, but as soon as **any** of the folders were done, the program quit instead of waiting for the other folders.
