### ISSUE TITLE
Album arts + dat files are generated even when there's an entry for them in the archive folder

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#10]
I had a new song to my collection, and wanted to see how the numbering will work when a `dat` file of existing music already exists in `archive/` folder.

Spoiler: new album arts + dat files containing the old existing ones were generated.

This bug must've crept in some releases prior because i tested this situation a few days back, the `archive/` folder was being accounted for. New files were not generated if there was a dat file containing those entries in the `archive/` folder

**Comment by jojo2357** [comment]
Well the next version will be another overhaul. I think if you ran it again it would work since now there are artists to account for and i assume your old archive didnt

**Comment by RoguedBear** [comment]
I hoped it would work again after regenerating the dat files but it didn't 😕.
So I started fresh, recloned the repo generated files for my old music collection (files without the new music), copied to dat file to `archive/` folder and re ran the script. 

From the logs i saw, the images were being generated again despite the dat being in `archive/` folder

**Comment by jojo2357** [comment]
I believe you and once i finish the new version it will be a lot better. But hey, the current version is better than nothing for now

**Comment by jojo2357** [comment]
@RoguedBear the most recent commit *should* help but may not since i have not rigorously tested it quite yet

**Comment by RoguedBear** [comment]
Yep! The new commit fixed it!!!

But also in this new commit a new problem (not with the program, but with music files) emerged and I don't know how it could be addressed.

So in an album when there are more than 1 artist for a particular song, duplicate entries for the album art are created. (I don't even know whether they can be called duplicates, because technically they are unique cuz of different artists).

Here's a sample image of what I'm talking about:

![image](https://user-images.githubusercontent.com/39442192/112715564-e2a56d00-8f06-11eb-8b64-20a3cb4509ad.png)

The original entry for the same album at line no 12:
`12 | ~how i'm feeling~==9==Lauv`
Even after the new update to include artist names in the dat files, only a single entry for this album was there

So in this album there were a few songs, where more artists collaborated and hence their names are in the metadata. `Album artist` field is `Lauv` for all songs, and for collabs, `Contributing Artists` field contains their names .


Edit: What i am thinking maybe put all the `contributing artists`  for a particular album on the same line. So when a song with `Album Artist` and `Contributing Artist` match an entry in the dat file that same line could be used for all the songs of the same artist but different contributing artist.

or

ignore the contributing artists altogether

**Comment by jojo2357** [comment]
My solution would be to just combine identical album arts to reference the same key so when it does that it will make new lines but not new arts. This would be particularly helpful in cases where caps is changing

**Comment by RoguedBear** [comment]
This seems to be a better solution actually 😄

**Comment by jojo2357** [comment]
I didnt get a chance to test this but i think it is patched @RoguedBear 

Just remember that using archives will simply ignore instead of appending. To append, just rerun and everything in the generated output folders will be ignored and then appended accordingly

**Comment by jojo2357** [comment]
Pls verify this as well?

**Comment by RoguedBear** [comment]
> 
> 
> Pls verify this as well?

oh yes I forgot to close this issue. 

This part is also working great. I love the way how new songs are appended into existing dat files.
