### ISSUE TITLE
actions bot needs to be updated to properly mention album name with multiple contributing artists under their respective headings

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#16]
Since multiple artists are now officially added in the Library folder, I've noticed that when multiple artist names are present in the song's metadata and extracted they're separated by forward slash. This is also visible in some parts of the file [Albums_in_MDRP](Albums_in_MDRP.md) such as:
https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/3a4cd04666da76cfe17a1c0fe7975190aab433c2/Albums_in_MDRP.txt#L910

And since the forward slash appears to be the delimiter for multiple artists in a mp3 tag, so what i'm suggesting is that I take this album name and mention it under all the artists' heading in this file whose names are joined together with a forward slash. 
Example referring this line, I'd put `Play` under their (`Alan Walker`, `K-391`, `Tungevaag`, `Mangoo`) headings

But there also also exceptions in this 'forward-slash-delimiter' rule where artists who have a forward slash in their name as on this line with the band `AC/DC` could be separated into `AC` & `DC` which I'm sure no one would like 😄 

https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/3a4cd04666da76cfe17a1c0fe7975190aab433c2/Albums_in_MDRP.txt#L23

So, I would either have to add and maintain a whitelist or use an API to check whether "the artist with forward slashes in the name" exists or not (for this I would have to search for an API, or find a way to get that information)

If this plan is approved, I will work on this when I get time during the weekends.
If you have some suggestions to deal with this issue, then do let me know and I would be happy to consider them.

**Comment by jojo2357** [comment]
I wouldnt be too sure about that since @Smaltin has an uncanny way of finding Japanese artists with random characters. The library extracts and separates by `==` so if the artist as listed in the mp3 is in that format, i would say too bad lol. MDRP is smart enough that if a song with any of those artists came up that it would accept it and show the art so the problem is solely here. If you can make it work for 99% of cases (i would look at all the anime music first) then sure go ham just be careful.

**Comment by RoguedBear** [comment]
> The library extracts and separates by `==` so if the artist as listed in the mp3 is in that format

I don't understand this line. By multiple artists I meant that in an album there could be a few songs that have had collaborations with other artists. Then in that case they are separated by `==`? Yes. That is no problem.

But if you see this snippet from the dat file generated from the recent commit:

```
...

Slow Grenade==26==Ellie Goulding/Lauv
...
~how i'm feeling~==29==Lauv==Lauv & LANY==Lauv/BTS==Lauv & Troye Sivan==Lauv/Sofia Reyes

...

```

For a single song containing multiple artists, the output as shown above is what you would get for an individual song.
 (In windows file properties or in Musicbee, multiple artists would be separated by `;` _while editing from their menu_, but when programs extract this metadata it gets converted into a forward slash it seems)

---
> i would say too bad lol. MDRP is smart enough that if a song with any of those artists came up that it would accept it and show the art so the problem is solely here

I know, and I agree with that. This issue just belongs to this summary file because it looks kinda obnoxious when you randomly come across multiple artists written with joint forward slashes. 😅 

---
> I wouldnt be too sure about that since \@Smaltin has an uncanny way of finding Japanese artists with random characters

> If you can make it work for 99% of cases (i would look at all the anime music first) ...

Oh boi! 😂 
In that case it would be better I maintain a gist and then manually lookout for those artists or @Smaltin  report artists with forward slashes and I'll add them to the gist

**Comment by jojo2357** [comment]
Actually, come to think about it Im torn because on the one hand, it would definitely be nice to have them listed properly. On the other hand, maintaining a whole gist sounds like making a second library which sounds redundant :/ A ctrl + f for k-391 would still find the collab with AW as well as any solo albums. All im saying is that I wont maintain it myself unless i can automate it (i probably can maybe maybe not)

PS with mdrp are you getting more mp3's? Just wondering cuz hey album art + drp definitely got me into mp3's more

**Comment by RoguedBear** [comment]
It doesn't sound like there would be too much work in maintaining a gist because afterall it's just names of artists containing a forward slash in their names. I would be happy to maintain that list. 
For the reporting part, I guess the user who had their albums merged to the main branch could go through the list once to see whether their artists' names are alright or not and create an issue to have it updated..
But I don't think I can count on that _entirely_.

I'll have to put more time into researching this stuff. A way to check whether "artist with forward slashes in name" is real or not, maybe through spotify or youtube music (`spotdl` kinda uses YT Music to search for music iirc). 

Feel free to close this issue for the time being. I'll reopen it when I find something.

---
> PS with mdrp are you getting more mp3's? Just wondering cuz hey album art + drp definitely got me into mp3's more

Yeah, it's been a mix of situations that got me into mp3s. College got me into discord, and due to some recent personal circumstances I have a limited daily internet. So I had to stop using spotify and get into r/DataHoarders stuff.

And now when I see my collection so organised and ✨ rich with art ✨ it feel's rewarding in a way.
Couple that up with that art being visible on Discord without spotify? oh boy it has some goood FOSS vibes.
I see this project as an open sourced alternative to over spotify's reign of rich presence in discord. 
There's an alternative now for people to broadcast their rich presence to their friends from their offline collection and w/o spotify getting in the way.

(ps a big shoutout to @dsdude123 for this idea and starting this project and to you and @Smaltin  for developing this project further!!!)
