### ISSUE TITLE
Java Script runs out of Memory

### ISSUE THREAD

**Issue by MeisterErikson** [jojo2357/Music-Discord-Rich-Presence-Library#19]
Hi, I wanted to get the album covers of my 244 albums and everytime I want to do it I get the error "Java Script runs out of memory" . I have 16gb of ram. Could you please help me?

**Comment by jojo2357** [comment]
Can you provide any more information? The full error log, if you are using the exe or the js itself, if you are running other apps at the same time, etc because i have never gotten this issue so i need some more insights

**Comment by MeisterErikson** [comment]
I don´t know if this is the full error log, but it says "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory"

**Comment by MeisterErikson** [comment]
Ok here is the full one:

<--- Last few GCS --->
[14796:00000292D0842890] [14796:00000292D0042890]
142561 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.5 / 0.0 ms 142620 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.8 / 0.0 ms
(average mu = 0.093, current mu = 0.000) last resort GC in old space requested (average mu = 0.049, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace ==========================
@: ExitFrame [pc: 00007FF7F230234D]
1: ConstructFrame (pc: 00007FF7F228298A] Security context: @xo2adbbc8e8d1 
2: slice [ee0002ADBBC8E641](this=0x0008035bef51 ,0,89735) 3: storeBuffer(aka storeBuffer) [0000036BB49DD4B9] [C:\snapshot\itunes-artwork-finder\node_modules\jsmediatags\build2\NodeFileReader.js:125] [bytecode=0000027FC40F8769 offset=34](this=0x03cb452884b1 ,0...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by MeisterErikson** [comment]
<--- Last few GCS --->
[14796:00000292D0842890] [14796:00000292D0042890]
142561 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.5 / 0.0 ms 142620 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.8 / 0.0 ms
(average mu = 0.093, current mu = 0.000) last resort GC in old space requested (average mu = 0.049, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace ==========================
@: ExitFrame [pc: 00007FF7F230234D]
1: ConstructFrame (pc: 00007FF7F228298A] Security context: @xo2adbbc8e8d1 
2: slice [ee0002ADBBC8E641](this=0x0008035bef51 ,0,89735) 3: storeBuffer(aka storeBuffer) [0000036BB49DD4B9] [C:\snapshot\itunes-artwork-finder\node_modules\jsmediatags\build2\NodeFileReader.js:125] [bytecode=0000027FC40F8769 offset=34](this=0x03cb452884b1 ,0...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by jojo2357** [comment]
Thats interesting. I havent seen this sort of thing before. Maybe break up all the files into q couple of parts? I have only testing with my 20 albums and rouged bear had a bit more than me so maybe thats the issue
