### ISSUE TITLE
Suggestion: choice whether to overwrite the already generated files or append to the generated files

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#2]
### Problem:
When you generate album arts + dat file for a directory, new folders are generated in the repo root [`groove0`, `musicbee0`, ...].
But if these folders are already present then those files and the dat file are deleted and overwritten.

If a user is generating album arts and config files for music spread across their computer, it may be cumbersome for them to copy the existing ones somewhere and then generate files again for another folder

### Suggestion:
If an existing config folder is detected ask the choice whether to overwrite them or to append the new album art + config file to that folder continuing the numbering from the previously generated files

**Comment by jojo2357** [comment]
oh i didnt even think of that one. Theres already a system in place for something like this but it doesn't work for the mp3's (only the elusive dat one).

**Comment by jojo2357** [comment]
Okay, the fix is to put your generated dat files in a folder called `archive` the computer will not make duplicates and will start working on new albums. Ill leave this open for now since i think there is a better solution

**Comment by jojo2357** [comment]
This was sort of addressed in the most recent commit as the user can either append to current apps (by simply rerunning) or create new ones (by deleting the other folders)

**Comment by RoguedBear** [comment]
Since this feature works I'll be okay closing it.
