### ISSUE TITLE
Java Script Heap Out of memory

### ISSUE THREAD

**Issue by MeisterErikson** [jojo2357/Music-Discord-Rich-Presence-Library#20]
Hi, I´ve already explained my problem, that when I want to load my covers the program says Java Script out of memory. Sadly I closed the old thread so I decided to create this one (sorry but sometimes my fingers are faster than my eyes). Here is the full error log:

<--- Last few GCS --->
[14796:00000292D0842890] [14796:00000292D0042890]
142561 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.5 / 0.0 ms 142620 ms: Mark-sweep 2048.5 (2054.1) -> 2048.5 (2054.1) MB, 58.8 / 0.0 ms
(average mu = 0.093, current mu = 0.000) last resort GC in old space requested (average mu = 0.049, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace ==========================
@: ExitFrame [pc: 00007FF7F230234D]
1: ConstructFrame (pc: 00007FF7F228298A] Security context: @xo2adbbc8e8d1 
2: slice [ee0002ADBBC8E641](this=0x0008035bef51 ,0,89735) 3: storeBuffer(aka storeBuffer) [0000036BB49DD4B9] [C:\snapshot\itunes-artwork-finder\node_modules\jsmediatags\build2\NodeFileReader.js:125] [bytecode=0000027FC40F8769 offset=34](this=0x03cb452884b1 ,0...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by jojo2357** [comment]
You can reopen issues if u close them btw. Anyway, see my comment there about getting around the issue

**Comment by MeisterErikson** [comment]
Okay I got it to work, but I have another problem. Everytime I want to load the jpegs into Discord Developer Portal in my groove application he doesn´t want to save the images. I can click save everytime and often but when he said saved and I reload the page to make sure it´s saved there are 0 images...

**Comment by jojo2357** [comment]
Thats a discord thing, wait a couple of minutes before retrying

**Comment by jojo2357** [comment]
This should no longer happen in the new processing code architecture
