### ISSUE TITLE
Unable to create a PR because groove0, spotify0, musicbee0 are in gitignore

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#3]
As `groove0`, `musicbee0`, `spotify0` are in `.gitignore`, comparing pull request across forks does not detect the commit with these folders added.

**Comment by jojo2357** [comment]
> Make a folder under Pending_User_Files

As per the readme. Please upload the raw output so i can make an app for them for everyone

**Comment by RoguedBear** [comment]
yes. I moved the 3 folders to `Pending_User_Files/RoguedBear/`, but git did not detect them, so after I commented out those lines locally in gitignore, i was able to commit the files in that folder.

But now I can't push to my fork because remote repo still has those 3 folders in gitignore

**Comment by RoguedBear** [comment]
wait, what do you mean by "raw output"?

**Comment by jojo2357** [comment]
the folders with the images and unedited dat files

**Comment by RoguedBear** [comment]
so I just move the images and the dat file into `Pending_User_Files/RoguedBear/` but not as `Pending_User_Files/RoguedBear/groove0`, `Pending_User_Files/RoguedBear/musicbee0`, `Pending_User_Files/RoguedBear/spotify0`?

**Comment by jojo2357** [comment]
put all the created folders under `RougedBear` (that means the latter, not the former)

**Comment by RoguedBear** [comment]
this is what i did originally but I couldn't commit those folders because git is ignoring those folders 

https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/004e9270ef0389c877e4975a65a5a90a3edb397d/.gitignore#L2

**Comment by jojo2357** [comment]
really even in a nested folder? thats strange let me look into that sorry

**Comment by jojo2357** [comment]
Ok my bad change the gitignore lines to be
```
groove[0-9]/*
spotify[0-9]/*
musicbee[0-9]/*
```
and then pr please.
